"""Add is_verified column to User model

Revision ID: 3723f94c4c6c
Revises: bb55f3a89c69
Create Date: 2025-07-20 12:34:56.789012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3723f94c4c6c'
down_revision = 'bb55f3a89c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # --- MODIFY THIS LINE ---
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
